/*! ****************************************************************************
 * ES6Kadoo v0.0.0-beta.10
 *
 * A template for writing pure ES6 Javascript libraries.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2020 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from {{boiler:name}} v{{boiler:name:version}}.
 * ************************************************************************** */
/*! Generated by Kadoo v0.0.0-beta.6 */
const $__ES6GLOB={};!function(t,e){"use strict";"function"==typeof define&&define.amd?define([""],e):"object"==typeof exports?module.exports=e(t):t.ES6Kadoo=e(t)}($__ES6GLOB,t=>{"use strict";let e={src:{prototypal:{},util:{util:{}}},extend:function(t,e){for(var o=Object.keys(e),n=0;n<o.length;n++)t[o[n]]=e[o[n]]}};return function(){const o=e.src.util.util,n=t.ES6Kadoo;let r;const i=function(t){const e=Object.create(r);return e._library={name:"ES6Kadoo",version:"0.0.0-beta.10"},e.name=t,e};i.NAME="ES6Kadoo",i.VERSION="0.0.0-beta.10",i._setTestMode=function(){return[]},i.noConflict=function(){return t.ES6Kadoo=n,this},r={whoami(){return this._library},getString:()=>o.getString(),getArray:()=>o.getArray()},e.src.prototypal=i}(),function(){const t={getString:()=>"I am a string!",getArray:()=>[1,2,3]};e.extend(e.src.util.util,t)}(),e.src.prototypal});export default $__ES6GLOB.ES6Kadoo;