/*! ****************************************************************************
 * ES6Kadoo v2.2.1
 *
 * A template for writing pure ES6 Javascript libraries.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2026 Mobilabs <contact@mobilabs.fr> (https://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from {{boiler:name}} v{{boiler:name:version}}.
 * ************************************************************************** */
/*! Generated by Kadoo v1.3.0 */
const $__ES6GLOB={};!function(t,o){"use strict";"function"==typeof define&&define.amd?define([""],o):"object"==typeof exports?module.exports=o(t):t.ES6Kadoo=o(t)}($__ES6GLOB,t=>{"use strict";let o={src:{prototypal:{},util:{util:{}}},extend:function(t,o){for(var e=Object.keys(o),n=0;n<e.length;n++)t[e[n]]=o[e[n]]}};return function(){const t=o.src.util.util,e=function(){const t=Object.create(r);return t._library={name:"ES6Kadoo",version:"2.2.1"},t};e.NAME="ES6Kadoo",e.VERSION="2.2.1";const n=globalThis.ES6Kadoo;e._setTestMode=function(){return[]},e.noConflict=function(){return globalThis.ES6Kadoo=n,this};const r={whoami(){return this._library},getString:()=>t.getString(),getArray:()=>t.getArray()};o.src.prototypal=e}(),function(){const t={getString:()=>"I am a string!",getArray:()=>[1,2,3]};o.extend(o.src.util.util,t)}(),o.src.prototypal});export default $__ES6GLOB.ES6Kadoo;