/*! ****************************************************************************
 * ES6Kadoo v1.0.12
 *
 * A template for writing pure ES6 Javascript libraries.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2023 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from {{boiler:name}} v{{boiler:name:version}}.
 * ************************************************************************** */
!/*! Generated by Kadoo v1.0.7 */
const $__ES6GLOB={};(function(t,e){"use strict";if(typeof define==="function"&&define.amd){define([""],e)}else if(typeof exports==="object"){module.exports=e(t)}else{t.ES6Kadoo=e(t)}})($__ES6GLOB,(t=>{"use strict";let e={src:{prototypal:{},util:{util:{}}}};e.extend=function(t,e){var r=Object.keys(e);for(var n=0;n<r.length;n++){t[r[n]]=e[r[n]]}};(function(){const r=e.src.util.util;const n=t.ES6Kadoo;let o;const i=function(){const t=Object.create(o);t._library={name:"ES6Kadoo",version:"1.0.12"};return t};i.NAME="ES6Kadoo";i.VERSION="1.0.12";i._setTestMode=function(){return[]};i.noConflict=function(){t.ES6Kadoo=n;return this};o={whoami(){return this._library},getString(){return r.getString()},getArray(){return r.getArray()}};e.src.prototypal=i})();(function(){function t(){return"I am a string!"}function r(){return[1,2,3]}const n={getString(){return t()},getArray(){return r()}};e.extend(e.src.util.util,n)})();return e.src.prototypal}));export default $__ES6GLOB.ES6Kadoo;